version: "3.3"
services:
  envoy-proxy:
    build:
      context: .
      dockerfile: ./.docker/envoy/Dockerfile
    networks:
      - statistico_internal
    environment:
      STATISTICO_RATINGS_HOST: statistico-ratings-grpc
      STATISTICO_RATINGS_PORT: 50051
    ports:
      - "9902:9902"
      - "8090:8090"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: statistico
      POSTGRES_PASSWORD: password
      POSTGRES_DB: statistico_ratings
    volumes:
      - .:/opt
    ports:
      - 5435:5432
    networks:
      - statistico-ratings_default

  console: &console
    build:
      dockerfile: .docker/Dockerfile
      context: .
    environment:
      DB_DRIVER: postgres
      DB_HOST: postgres
      DB_NAME: statistico_ratings
      DB_PASSWORD: password
      DB_USER: statistico
      DB_PORT: 5432
    tty: true
    links:
      - postgres
    networks:
      - statistico_internal
      - statistico-ratings_default

  statistico-ratings-grpc:
    <<: *console
    networks:
      - statistico_internal
      - statistico-ratings_default
    ports:
      - "50051"
    command: [ "./grpc", "--port 50051" ]

  migrate:
    <<: *console
    command: ["./bin/migrate"]

  test:
    build:
      dockerfile: .docker/test/Dockerfile
      context: .
    volumes:
      - .:/opt
    environment:
      DB_DRIVER: postgres
      DB_HOST: postgres
      DB_PASSWORD: password
      DB_NAME: statistico_ratings
      DB_USER: statistico
      DB_PORT: 5432
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - statistico-ratings_default

networks:
  statistico-ratings_default:
    external: false
  statistico_internal:
    external: true
